config/routes.rb
Rails.application.routes.draw do
  root to: 'dishes#index'
  resources :dishes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates :image, :name, :taste, :restaurant, :location, presence: true

  has_attached_file :image, styles: { 
    thumb: '100x100>',
    square: '200x200#',
    :medium => "640x" }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  def index
    @dishes = Dish.all 
  end 

  def new
    @dish = Dish.new 
  end 

  def create
    @dish = Dish.new(dish_params)
      binding.pry
    if @dish.save
      flash[:success] = "Your dish has been added!"
      redirect_to dishes_path
    else 
      flash.now[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end 

  def show

  end 

  def edit  

  end

  def update  
    if @dish.update_attributes(dish_params)
      flash[:success] = "Dish updated!"
      redirect_to(dish_path(@dish))
    else 
      flash.now[:alert] = "Update failed!"
      render :edit
    end 
  end 

  def destroy
    @dish.destroy
    redirect_to dishes_path
  end 

  private

  def set_dish
    @dish = Dish.find(params[:id])
  end 

  def dish_params  
    params.require(:dish).permit(:image, :description, :name, :price, :taste, :email, :restaurant, :full_meal, :location, :special, :vegetarian, :consistent)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper

def alert_for(flash_type)  
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end  

end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<h4>Welcome! Thank you for taking the time to fill out this form! Please fill it out CAREFULLY (we're still in beta)! And excuse the messiness - we're still learning! Our hope is to get enough data to launch a fully fledged app in just over a week! Feel free to share this with your friends! We need all the help we can get. Thank you for bringing your honesty to this project. Now.. <strong>Dish About It!</strong></h4>

<% if @dish.image? %>
  <div class="text-center">
    <%= image_tag @dish.image.url(:medium), class:'img-responsive' %>
  </div>
<% end %>
<div class="form-wrapper">
  <%= simple_form_for @dish, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group">
      <%= f.input :name, :label => 'What is the name of this dish as listed on the restaurants menu? Please be exact!  ' %>
    </div>
     <div class="form-group text-center">
      <%= f.input :price, :label => 'How much was this listed for on the menu? $', input_html: { min: '0'}  %>
    </div> 
    <div class="form-group text-center">
      <%= f.input :description, as: :text, :label => 'Enter your personal comments about this dish here  ' %>
    </div>
    <div class="form-group text-center">
      <h6>Please check the boxes to answer yes..</h6>
      <%= f.input :full_meal, :label => 'Would you consider this a full meal on its own?' %>
    </div>  
    <div class="form-group text-center">
      <%= f.input :consistent, :label => '(IF YOU HAVE EATEN THIS DISH BEFORE..) Is this dish consistent?' %>
    </div>  
    <div class="form-group text-center">
      <%= f.input :vegetarian, :label => 'Is this dish vegetarian?' %>
    </div>  
    <div class="form-group text-center">
      <%= f.input :special, :label => 'Is this dish a special? i.e. not on the regular menu?  ' %>
    </div>  
    <div class="form-group text-center">
      <%= f.input :restaurant, :label => "What is the name of the restaurant?" %>
    </div>  
    <div class="form-group text-center">
      <%= f.input :location, :label => "Please input the address of this location as detailed as possible! ex: '1234 Broad Street, New York, NY 10001' " %>
    </div>  
    <div class="form-group text-center">
      <%= f.input :taste, collection: (1..10), as: :radio_buttons, :label => 'How would you rate JUST the taste, from 1-10 ?'%>
    </div> 
    <div class="form-group text-center">
      <%= f.input :email, :label => "Add your email and we'll try to contact you when the app is up! "%>
    </div>  
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/dishes/edit.html.erb
<%= render 'form' %>
<div class="text-center edit-links">
  <%= link_to "Delete Dish", dish_path(@dish), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", dishes_path %>
</div>

app/views/dishes/index.html.erb
<h1>Dish</h1>

<div class="dishes-wrapper row .col-xs-6 .col-sm-4">
  <% @dishes.each do |dish| %>
    <div class="dish">
      <div class="dish-head">
        <div class="name .col-xs-6 .col-sm-4">
          <%= dish.name %>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag dish.image.url(:medium), class:'img-responsive'), dish_path(dish) %>
      </div>
      <p class="description .col-xs-6 .col-sm-4">
        <%= dish.description %>
      </p>
    </div>
  <% end %>
</div>

app/views/dishes/new.html.erb
<%= render 'form' %>

app/views/dishes/show.html.erb
<div class="dishes-wrapper row">
  <div class="dish">
    <div class="dish-head">
      <div class="name .col-xs-6 .col-sm-4">
        <%= @dish.name %>
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @dish.image.url(:medium), class:'img-responsive' %>
    </div>
    <p class="description .col-xs-6 .col-sm-4">
      <%= @dish.description %>
    </p>
    <div class="text-center edit-links">
      <%= link_to "Cancel", dishes_path %>
      |
      <%= link_to "Edit Dish", edit_dish_path(@dish) %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DishesForm</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="navbar-container">
          <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand">
              <%= link_to "Dish", root_path %> |  |  
              <%= link_to "New Dish", new_dish_path %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <section class="container-fluid">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>
      <%= yield %>
    </section>
  </body>
</html>